version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: ec2-user
